version: '3.8'

services:
  backend:
    build: .
    container_name: todo-backend-container
    ports:
      - "3001:3001"
    env_file:
      - ../.env  
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

